---
- hosts: default
  tasks:
    - name: Set authorized key for user by copying it from current user
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
